### ISSUE TITLE
将读取和写入Properties文件的工具类合为一个

### ISSUE THREAD

**Issue by runME** [yyud/sendmessage#2]
这里应该是划分为不同的方法，而不是划分成两个类，至少目前是不需要的，提供统一的操作入口（一个PropertisUtil）对用户使用更友好，并且这两个功能联系非常紧密，不足以放到不同类里

**Comment by yyudR** [comment]
将Properties文件读写合并为一个PropertiesHelper文件[PropertiesHelper.java](https://github.com/yyud/sendmessage/blob/master/src/main/java/com/issc/sendmessage/Utils/PropertiesHelper.java)
